import { NextResponse } from "next/server";

export const runtime = "nodejs";

/**
 * DEPRECATED / DISABLED.
 *
 * Sprint puzzles used to be generated by the client and registered here, which
 * let a scripted client seed trivial puzzles and inflate its score. Puzzles are
 * now generated server-side; use POST /api/sprint/next instead. This endpoint
 * exists only to explicitly reject the old (exploitable) flow.
 */
export async function POST() {
  return NextResponse.json(
    {
      error: "gone",
      message:
        "Client puzzle registration is disabled. Puzzles are generated server-side via /api/sprint/next.",
    },
    { status: 410 }
  );
}
